# Generated by Django 3.1.4 on 2020-12-09 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201210_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='date_filled',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='adults_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='children_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
